# Generated by Django 2.1.2 on 2018-10-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=200)),
				('customer_lastname', models.CharField(max_length=200)),
				('customer_address', models.CharField(max_length=200)),
				('customer_city', models.CharField(max_length=200)),
				('customer_zipcode', models.CharField(max_length=200)),
				('customer_state', models.CharField(max_length=200)),
            ],
        ),
    ]
